CC = /opt/gcc/gcc-12.1.0/bin/g++
MPCC = /opt/gcc/gcc-12.1.0/bin/g++
OPENMP = -fopenmp
CFLAGS = -std=c++14 -O3 -fopenmp
LIBS = -m64 -fPIC -fno-strict-aliasing -fexceptions -fopenmp -DNDEBUG -DIL_STD -lm -lpthread -ldl
TARGETS = Cell2Fire
all:	$(TARGETS)
Cell2Fire: Cell2Fire.o Cells.o FuelModelUtils.o ScottAndBurganKernel.o KitralKernel.o CanadianFBPKernel.o FuelModelPortugal.o Spotting.o ReadCSV.o ReadArgs.o Lightning.o WriteCSV.o DataGenerator.o
	$(CC) -o $@ $(LIBS) Cell2Fire.o Cells.o FuelModelUtils.o ScottAndBurganKernel.o KitralKernel.o CanadianFBPKernel.o FuelModelPortugal.o Spotting.o ReadCSV.o ReadArgs.o Lightning.o WriteCSV.o DataGenerator.o
Cell2Fire.o: Cell2Fire.cpp Cells.o FuelModelUtils.o ScottAndBurganKernel.o KitralKernel.o CanadianFBPKernel.o FuelModelPortugal.o Spotting.o ReadCSV.o ReadArgs.o WriteCSV.o DataGenerator.o
	$(CC) -c $(CFLAGS) Cell2Fire.cpp
Spotting.o: Spotting.cpp Spotting.h Cells.h
	$(CC) -c $(CFLAGS) Spotting.cpp
Cells.o: Cells.cpp Cells.h FuelModelUtils.o ScottAndBurganKernel.o KitralKernel.o CanadianFBPKernel.o FuelModelPortugal.o
	$(CC) -c $(CFLAGS) Cells.cpp
ReadCSV.o: ReadCSV.cpp ReadCSV.h 
	$(CC) -c $(CFLAGS) ReadCSV.cpp
ReadArgs.o: ReadArgs.cpp ReadArgs.h
	$(CC) -c $(CFLAGS) ReadArgs.cpp
Lightning.o: Lightning.cpp Lightning.h
	$(CC) -c $(CFLAGS) Lightning.cpp
Forest.o: Forest.cpp Forest.h
	$(CC) -c $(CFLAGS) Forest.cpp
WriteCSV.o: WriteCSV.cpp WriteCSV.h
	$(CC) -c $(CFLAGS) WriteCSV.cpp
FuelModelUtils.o: FuelModelUtils.cpp FuelModelUtils.h Cells.h
	$(CC) -c $(LIBS) $(CFLAGS) FuelModelUtils.cpp
ScottAndBurganKernel.o: ScottAndBurganKernel.cpp ScottAndBurganKernel.h FuelModelUtils.h Cells.h
	$(CC) -c $(LIBS) $(CFLAGS) ScottAndBurganKernel.cpp 
KitralKernel.o: KitralKernel.cpp FuelModelUtils.h KitralKernel.h Cells.h
	$(CC) -c $(LIBS) $(CFLAGS) KitralKernel.cpp 
CanadianFBPKernel.o: CanadianFBPKernel.cpp CanadianFBPKernel.h Cells.h
	$(CC) -c $(LIBS) $(CFLAGS) CanadianFBPKernel.cpp
FuelModelPortugal.o: FuelModelPortugal.cpp FuelModelUtils.h FuelModelPortugal.h Cells.h
	$(CC) -c $(LIBS) $(CFLAGS) FuelModelPortugal.cpp
DataGenerator.o: DataGenerator.cpp DataGenerator.h
	$(CC) -c $(LIBS) $(CFLAGS) DataGenerator.cpp
clean:
	rm -f Lightning.o ReadArgs.o ReadCSV.o Cell2Fire.o Cells.o Cell2Fire Spotting.o WriteCSV.o CanadianFBPKernel.o KitralKernel.o ScottAndBurganKernel.o FuelModelPortugal.o FuelModelUtils.o DataGenerator.o *.gch
	
DESTDIR = ~/bin
install: all
	mkdir -p $(DESTDIR)
	cp $(TARGETS) $(DESTDIR)
	echo "export PATH=\$$PATH:$(DESTDIR)" >> ~/.bashrc
uninstall: all
	rm -rf $(DESTDIR)/$(TARGETS) 

